services:
  db:
    image: mysql:5.7.44
    platform: linux/amd64
    env_file:
      - mysql.env
    volumes:
      - db_data:/var/lib/mysql

  web:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DATABASE_HOST=db
      - DATABASE_USER=root
      - DATABASE_PASSWORD=letmein1
      - DATABASE_DB=asset_management
    command: ["./wait-for-it.sh", "db:3306", "--", "uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]

volumes:
  db_data:
